"""cria tabela atendimentos

Revision ID: 067f9182efaf
Revises: 189f47eb4fa1
Create Date: 2026-08-07 14:40:35.427960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067f9182efaf'
down_revision = '189f47eb4fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id_atendimento', sa.Integer(), nullable=False),
    sa.Column('data_atendimento', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('protocolo', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('km_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('origem', sa.String(length=255), nullable=True),
    sa.Column('destino', sa.String(length=255), nullable=True),
    sa.Column('valor_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_pedagio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_hora_parada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_hora_trabalhada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_hora_parada', sa.Integer(), nullable=False),
    sa.Column('quantidade_hora_trabalhada', sa.Integer(), nullable=False),
    sa.Column('quantidade_patins', sa.Integer(), nullable=False),
    sa.Column('cobrar_pedagio', sa.Boolean(), nullable=False),
    sa.Column('cobrar_hora_parada', sa.Boolean(), nullable=False),
    sa.Column('cobrar_hora_trabalhada', sa.Boolean(), nullable=False),
    sa.Column('usar_patins', sa.Boolean(), nullable=False),
    sa.Column('status_operacional', sa.String(length=30), nullable=False),
    sa.Column('status_financeiro', sa.String(length=40), nullable=False),
    sa.Column('fk_tabela_valores_id_tabela_valores', sa.Integer(), nullable=False),
    sa.Column('fk_cliente_id_cliente', sa.Integer(), nullable=True),
    sa.Column('fk_motorista_id_motorista', sa.Integer(), nullable=True),
    sa.Column('fk_caminhao_id_caminhao', sa.Integer(), nullable=True),
    sa.Column('fk_usuario_id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_caminhao_id_caminhao'], ['caminhoes.id_caminhao'], ),
    sa.ForeignKeyConstraint(['fk_cliente_id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['fk_motorista_id_motorista'], ['motoristas.id_motorista'], ),
    sa.ForeignKeyConstraint(['fk_tabela_valores_id_tabela_valores'], ['tabela_valores.id_tabela_valores'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_atendimento')
    )
    op.create_table('veiculos_rebocados',
    sa.Column('fk_atendimento_id_atendimento', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['fk_atendimento_id_atendimento'], ['atendimentos.id_atendimento'], ),
    sa.PrimaryKeyConstraint('fk_atendimento_id_atendimento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculos_rebocados')
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
