"""cria tabela tabela_valores

Revision ID: 189f47eb4fa1
Revises: 63e11442ff03
Create Date: 2026-08-05 15:53:38.145324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189f47eb4fa1'
down_revision = '63e11442ff03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_valores',
    sa.Column('id_tabela_valores', sa.Integer(), nullable=False),
    sa.Column('valor_saida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_km_excedente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fk_tipo_servico_id_tipo_servico', sa.Integer(), nullable=False),
    sa.Column('fk_administradora_id_administradora', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_administradora_id_administradora'], ['administradoras.id_administradora'], ),
    sa.ForeignKeyConstraint(['fk_tipo_servico_id_tipo_servico'], ['tipos_servico.id_tipo_servico'], ),
    sa.PrimaryKeyConstraint('id_tabela_valores')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_valores')
    # ### end Alembic commands ###
