"""cria tabela clientes

Revision ID: 63e11442ff03
Revises: 65062e53ffda
Create Date: 2026-08-04 22:38:05.505822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e11442ff03'
down_revision = '65062e53ffda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fk_administradora_id_administradora', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_administradora_id_administradora'], ['administradoras.id_administradora'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
