"""cria tabela tipos_servico

Revision ID: 65062e53ffda
Revises: ac4ff6cba850
Create Date: 2026-08-04 22:16:25.209044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65062e53ffda'
down_revision = 'ac4ff6cba850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_servico',
    sa.Column('id_tipo_servico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_servico'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_servico')
    # ### end Alembic commands ###
