"""permite valores nulos na tabela de valores

Revision ID: 71687166ed6f
Revises: ade020f74175
Create Date: 2026-08-15 18:26:39.221804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71687166ed6f'
down_revision = 'ade020f74175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_valores', schema=None) as batch_op:
        batch_op.alter_column('valor_saida',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('valor_km_excedente',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_valores', schema=None) as batch_op:
        batch_op.alter_column('valor_km_excedente',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('valor_saida',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###
