"""Cria tabela motoristas

Revision ID: a282f2999050
Revises: facaf25a0aa9
Create Date: 2026-08-01 21:17:22.798302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a282f2999050'
down_revision = 'facaf25a0aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motoristas',
    sa.Column('id_motorista', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('numero_cnh', sa.String(length=20), nullable=False),
    sa.Column('validade_cnh', sa.Date(), nullable=False),
    sa.Column('validade_toxicologico', sa.Date(), nullable=False),
    sa.Column('categoria_cnh', sa.String(length=5), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_motorista'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('numero_cnh')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motoristas')
    # ### end Alembic commands ###
