"""cria tabela administradoras

Revision ID: ac4ff6cba850
Revises: b3161cdd7899
Create Date: 2026-08-04 19:39:31.532002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4ff6cba850'
down_revision = 'b3161cdd7899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradoras',
    sa.Column('id_administradora', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cliente_proprio', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_administradora'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administradoras')
    # ### end Alembic commands ###
