"""permite campos opcionais em veiculo rebocado

Revision ID: ade020f74175
Revises: 067f9182efaf
Create Date: 2026-08-15 17:49:24.223456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade020f74175'
down_revision = '067f9182efaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos_rebocados', schema=None) as batch_op:
        batch_op.alter_column('placa',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculos_rebocados', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('placa',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
