"""cria tabela caminhoes

Revision ID: b3161cdd7899
Revises: a282f2999050
Create Date: 2026-08-02 16:39:07.180332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3161cdd7899'
down_revision = 'a282f2999050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caminhoes',
    sa.Column('id_caminhao', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_caminhao'),
    sa.UniqueConstraint('placa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caminhoes')
    # ### end Alembic commands ###
